services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command: --configFile=/etc/traefik/traefik.yml
    networks:
      - deploy-net
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml
      - ./logs/traefik:/var/log/traefik

networks:
  deploy-net:
    external: true
