#For dynamic configuration
api:
    dashboard: true
    insecure: true

entryPoints:
    web:
        address: ":80"

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
        network: "deploy-net"
    file:
        filename: /etc/traefik/dynamic_conf.yml

log:
  level: INFO
  filePath: "/var/log/traefik/access.log"
  format: json

# metrics:
#   prometheus:  # Enable Prometheus metrics
#     addRoutersLabels: true  # Add labels for routers in metrics
#     addServicesLabels: true # Add labels for services in metrics
#     buckets: [0.1, 0.3, 1.2, 5.0]  # Custom histogram buckets for response times
#     entryPoint: web
#     addEntryPointsLabels: true # Add labels for entrypoints in metrics
